
//! Autogenerated weights for `pallet_dao_core`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-01-09, STEPS: `20`, REPEAT: 10, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HOSTNAME: `Christians-MBP.fritz.box`, CPU: `<UNKNOWN>`
//! EXECUTION: None, WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/genesis-dao
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_dao_core
// --extrinsic
// *
// --steps
// 20
// --repeat
// 10
// --output
// pallets/dao-core/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions for `pallet_dao_core`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_dao_core::WeightInfo for WeightInfo<T> {
	// Storage: DaoCore Daos (r:1 w:1)
	fn create_dao() -> Weight {
		// Minimum execution time: 35_000 nanoseconds.
		Weight::from_ref_time(36_000_000)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	// Storage: DaoCore Daos (r:1 w:1)
	fn destroy_dao() -> Weight {
		// Minimum execution time: 37_000 nanoseconds.
		Weight::from_ref_time(37_000_000)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	// Storage: DaoCore Daos (r:1 w:1)
	// Storage: DaoCore CurrentAssetId (r:1 w:1)
	// Storage: Assets Asset (r:1 w:1)
	// Storage: Assets Account (r:1 w:1)
	// Storage: Assets Metadata (r:1 w:1)
	fn issue_token() -> Weight {
		// Minimum execution time: 75_000 nanoseconds.
		Weight::from_ref_time(76_000_000)
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(5))
	}
}
